# Meme Mayhem Settings File

[PLAYER]
Skin = "Blue"

[CONTROLS]
MoveUp = "w"
MoveLeft = "a"
MoveDown = "s"
MoveRight = "d"
FireWeapon = "LMB"
ReloadWeapon = "r"

[RENDERING]
VSync = true
Fullscreen = true

