
# A machinegun that when fired the enemy is stuned an deals a small amount of damge when stuned
Name = "Chewiecatt's machinegun"
Type = "Automatic" 
ReloadTime = 6.5
MagSize = 100
ShotDamage = 3